<?php
/**
内容--栏目管理
 */

namespace app\manage\controller;


use controller\Backend;
use library\Tree;
use think\App;
use app\common\model\Article as articleModel;


class Article extends Backend
{

    /**
     * area模型对象
     * @var app\common\model\Article
     */
    protected $article_list;
    protected $model;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new articleModel();
        $where = $this->build_params();
        $this->article_list = $this->model
            ->alias('a')
            ->field('a.*,category.name as category_name')
            ->join('category','a.category_id = category.id')
            ->where($where)
//            ->order('c.id desc')
            ->select()
            ->toArray();
//        $category_tree_obj = Tree::instance();
//        $category_tree_obj->init($data);
//        $this->category_list = $category_tree_obj->getTreeList($category_tree_obj->getTreeArray(0));
    }

    public function index()
    {
        if( $this->request->isAjax() ){
//            var_dump($this->category_list);die;
            return layui_table_data($this->article_list);
        }
        return $this->fetch();
    }

}